/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CrearPDFHandler;
import Controlador.GuardarPDFenBDHandler;
import Controlador.ManejoDeRespaldo;
import Modelo.ConocimientoDeInformatica;
import Modelo.Curriculum;
import Modelo.DAO.DAO_conocimienoDeInformatica;
import Modelo.DAO.DAO_idioma;
import Modelo.Experiencia;
import Modelo.Idioma;
import Modelo.Referencia;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Date;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Cheloz
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public static Curriculum c;
    public static List<ConocimientoDeInformatica> conocimientosDeInformaticaSeleccionados;
    public static List<Idioma> idiomasSeleccionados;
    public static List<Experiencia> experienciasLaboralesAgregadas;
    public static List<Referencia> referenciasAgregadas;

    private List<String> nacionalidades;
    private List<String> estadosCiviles;
    private List<String> nivelesDeEstudio;
    private List<String> ocupaciones;
    private List<String> disponibilidades;

    private DAO_idioma di;
    private DAO_conocimienoDeInformatica dci;

    private List<Idioma> idiomas;
    private List<ConocimientoDeInformatica> conocimientosDeInformatica;

    public static ManejoDeRespaldo regulador;

    private HiloParaRespaldar hiloParaRespaldar;
    private HiloParaRestaurar hiloParaRestaurar;

    public static Object cerrojo = new Object();

    public GUI() throws ClassNotFoundException, SQLException {
        regulador = new ManejoDeRespaldo();

        regulador.restaurarBD("respaldo.sql");

        //hiloParaRestaurar = new HiloParaRestaurar();
        hiloParaRespaldar = new HiloParaRespaldar();
        hiloParaRespaldar.start();

       //hiloParaRespaldar.start();
        initComponents();

        di = new DAO_idioma(null);
        dci = new DAO_conocimienoDeInformatica(null);

        idiomas = di.read();
        conocimientosDeInformatica = dci.read();

        nacionalidades = new ArrayList<String>();
        estadosCiviles = new ArrayList<String>();
        nivelesDeEstudio = new ArrayList<String>();
        ocupaciones = new ArrayList<String>();
        disponibilidades = new ArrayList<String>();

        rellenarComboboxes();
        calendar.setSelectedDate(LocalDate.now());
        rbtMasculino.setSelected(true);

        experienciasLaboralesAgregadas = new ArrayList<>();
        referenciasAgregadas = new ArrayList<>();
        idiomasSeleccionados = new ArrayList<>();
        conocimientosDeInformaticaSeleccionados = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSexo = new javax.swing.ButtonGroup();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        lblFechaDeNacimiento = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblNacionalidad = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblNivelDeEstudio = new javax.swing.JLabel();
        lblOcupacion = new javax.swing.JLabel();
        lblDisponibilidad = new javax.swing.JLabel();
        cboNacionalidad = new javax.swing.JComboBox();
        cboEstadoCivil = new javax.swing.JComboBox();
        rbtMasculino = new javax.swing.JRadioButton();
        rbtFemenino = new javax.swing.JRadioButton();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        cboNivelDeEstudio = new javax.swing.JComboBox();
        cboDisponibilidad = new javax.swing.JComboBox();
        cboOcupacion = new javax.swing.JComboBox();
        btn_crearPdf = new javax.swing.JButton();
        calendar = new com.github.lgooddatepicker.components.CalendarPanel();
        lblIdiomas = new javax.swing.JLabel();
        lblConocimientosDeInformatica = new javax.swing.JLabel();
        cboIdiomas = new javax.swing.JComboBox();
        cboConInfo = new javax.swing.JComboBox();
        lblExperiencia = new javax.swing.JLabel();
        lblReferencias = new javax.swing.JLabel();
        btnAgregarIdioma = new javax.swing.JButton();
        btnAgregarConocimientoInformatica = new javax.swing.JButton();
        txtNombreReferencia = new javax.swing.JTextField();
        txtApellidoReferencia = new javax.swing.JTextField();
        txtCargoReferencia = new javax.swing.JTextField();
        txtTelefonoReferencia = new javax.swing.JTextField();
        spnAnios = new javax.swing.JSpinner();
        txtCargoExperiencia = new javax.swing.JTextField();
        lblAñosExperiencia = new javax.swing.JLabel();
        btnAgregarExperiencia = new javax.swing.JButton();
        btnAgregarReferencia = new javax.swing.JButton();
        txtLugarExperiencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        lblApellido.setText("Apellido:");

        lblFechaDeNacimiento.setText("Fecha de nacimiento:");

        lblRut.setText("Rut:");

        lblNacionalidad.setText("Nacionalidad:");

        lblEstadoCivil.setText("Estado civil:");

        lblSexo.setText("Sexo:");

        lblTelefono.setText("Teléfono:");

        lblCorreo.setText("Correo:");

        lblDireccion.setText("Dirección:");

        lblNivelDeEstudio.setText("Nivel de estudio:");

        lblOcupacion.setText("Ocupación:");

        lblDisponibilidad.setText("Disponibilidad:");

        cboNacionalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGroupSexo.add(rbtMasculino);
        rbtMasculino.setText("Masculino");

        btnGroupSexo.add(rbtFemenino);
        rbtFemenino.setText("Femenino");

        cboNivelDeEstudio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboDisponibilidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboOcupacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_crearPdf.setText("Crear PDF");
        btn_crearPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearPdfActionPerformed(evt);
            }
        });

        lblIdiomas.setText("Idiomas:");

        lblConocimientosDeInformatica.setText("Conocimientos de informática:");

        cboIdiomas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboConInfo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblExperiencia.setText("Experiencia laboral:");

        lblReferencias.setText("Referencias:");

        btnAgregarIdioma.setText("Agregar");
        btnAgregarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarIdiomaActionPerformed(evt);
            }
        });

        btnAgregarConocimientoInformatica.setText("Agregar");
        btnAgregarConocimientoInformatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarConocimientoInformaticaActionPerformed(evt);
            }
        });

        txtNombreReferencia.setText("Nombre?");
        txtNombreReferencia.setToolTipText("Nombre:");
        txtNombreReferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alClickear(evt);
            }
        });
        txtNombreReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreReferenciaActionPerformed(evt);
            }
        });

        txtApellidoReferencia.setText("Apellido?");
        txtApellidoReferencia.setToolTipText("Apellido:");
        txtApellidoReferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                referenciaApellidoFocusGained(evt);
            }
        });

        txtCargoReferencia.setText("Cargo?");
        txtCargoReferencia.setToolTipText("Cargo");
        txtCargoReferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                referenciaCargoFocusGained(evt);
            }
        });

        txtTelefonoReferencia.setText("Teléfono?");
        txtTelefonoReferencia.setToolTipText("Teléfono:");
        txtTelefonoReferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoReferenciaFocusGained(evt);
            }
        });

        txtCargoExperiencia.setText("Cargo?");
        txtCargoExperiencia.setToolTipText("Cargo desempeñado:");

        lblAñosExperiencia.setText("Años:");
        lblAñosExperiencia.setToolTipText("");

        btnAgregarExperiencia.setText("Agregar");
        btnAgregarExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarExperienciaActionPerformed(evt);
            }
        });

        btnAgregarReferencia.setText("Agregar");
        btnAgregarReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarReferenciaActionPerformed(evt);
            }
        });

        txtLugarExperiencia.setText("Lugar?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDireccion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDireccion))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNivelDeEstudio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboNivelDeEstudio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTelefono)
                            .addGap(18, 18, 18)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblOcupacion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboOcupacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDisponibilidad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboDisponibilidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCorreo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCorreo)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblNombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNombre))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblApellido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtApellido))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblRut)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtRut))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblEstadoCivil)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblNacionalidad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboNacionalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblSexo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbtMasculino)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbtFemenino))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReferencias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCargoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefonoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarReferencia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblExperiencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLugarExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCargoExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAñosExperiencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarExperiencia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblConocimientosDeInformatica)
                                .addGap(18, 18, 18)
                                .addComponent(cboConInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarConocimientoInformatica))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaDeNacimiento)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIdiomas)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAgregarIdioma)))))
                        .addContainerGap(233, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btn_crearPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaDeNacimiento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellido))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRut)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNacionalidad)
                            .addComponent(cboNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstadoCivil)
                            .addComponent(cboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdiomas)
                    .addComponent(cboIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarIdioma))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexo)
                            .addComponent(rbtMasculino)
                            .addComponent(rbtFemenino)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelefono)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblConocimientosDeInformatica)
                                    .addComponent(cboConInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregarConocimientoInformatica))
                                .addGap(17, 17, 17)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCorreo)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblExperiencia)
                                .addComponent(txtLugarExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCargoExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAñosExperiencia)
                                .addComponent(spnAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAgregarExperiencia)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReferencias)
                    .addComponent(txtNombreReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarReferencia))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelDeEstudio)
                    .addComponent(cboNivelDeEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOcupacion)
                    .addComponent(cboOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_crearPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisponibilidad)
                    .addComponent(cboDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btn_crearPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearPdfActionPerformed
        // TODO add your handling code here:

        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String rut = txtRut.getText();
        String correo = txtCorreo.getText();
        String telefono = txtTelefono.getText();
        String direccion = txtDireccion.getText();
        Boolean esHombre = true;

        if (rbtFemenino.isSelected()) {
            esHombre = false;
        }

        String nacionalidad = cboNacionalidad.getSelectedItem().toString();
        String esttadoCivil = cboEstadoCivil.getSelectedItem().toString();
        String nivelDeEstudio = cboNivelDeEstudio.getSelectedItem().toString();
        String ocupacion = cboOcupacion.getSelectedItem().toString();
        String disponibilidad = cboDisponibilidad.getSelectedItem().toString();

        c = new Curriculum();
        c.setNombre(nombre);
        c.setApellido(apellido);
        c.setRut(rut);
        c.setCorreo(correo);
        c.setTelefono(telefono);
        c.setDireccion(direccion);
        c.setEsHombre(esHombre);

        c.setNacionalidad(nacionalidad);
        c.setEstadoCivil(esttadoCivil);
        c.setNivelDeEstudio(nivelDeEstudio);
        c.setOcupación(ocupacion);
        c.setDisponibilidad(disponibilidad);
        c.setDireccion(direccion);

        //calendar.getSelectedDate().toString();
        Date fechaDeNacimiento = (Date) Date.from(calendar.getSelectedDate().atStartOfDay(ZoneId.systemDefault()).toInstant());
        java.sql.Date fechaSQL = new java.sql.Date(fechaDeNacimiento.getTime());
        c.setFechaNacimiento(fechaSQL);

        CrearPDFHandler.crearArchivoDePDF();
        GuardarPDFenBDHandler obj = new GuardarPDFenBDHandler();
        try {

            obj.guardarPDF();
            // regulador.crearRespaldoBD();
            conocimientosDeInformaticaSeleccionados.clear();
            idiomasSeleccionados.clear();
            referenciasAgregadas.clear();
            experienciasLaboralesAgregadas.clear();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtNombre.setText("");
        txtApellido.setText("");
        txtRut.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");

    }//GEN-LAST:event_btn_crearPdfActionPerformed

    private void txtNombreReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreReferenciaActionPerformed

    private void alClickear(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alClickear
        txtNombreReferencia.setText("");
    }//GEN-LAST:event_alClickear

    private void referenciaApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_referenciaApellidoFocusGained
        txtApellidoReferencia.setText("");
    }//GEN-LAST:event_referenciaApellidoFocusGained

    private void referenciaCargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_referenciaCargoFocusGained
        txtCargoReferencia.setText("");
    }//GEN-LAST:event_referenciaCargoFocusGained

    private void txtTelefonoReferenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoReferenciaFocusGained
        txtTelefonoReferencia.setText("");
    }//GEN-LAST:event_txtTelefonoReferenciaFocusGained

    private void btnAgregarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIdiomaActionPerformed

        try {

            idiomasSeleccionados.add(di.findByName((String) cboIdiomas.getSelectedItem()));

        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Idioma guardado");
    }//GEN-LAST:event_btnAgregarIdiomaActionPerformed

    private void btnAgregarConocimientoInformaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConocimientoInformaticaActionPerformed

        try {

            conocimientosDeInformaticaSeleccionados.add(dci.findByName((String) cboConInfo.getSelectedItem()));

        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Conocimiento de informática guardado");


    }//GEN-LAST:event_btnAgregarConocimientoInformaticaActionPerformed

    private void btnAgregarExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarExperienciaActionPerformed
        String cargo = txtCargoExperiencia.getText();
        int anios = (Integer) spnAnios.getValue();
        String lugar = txtLugarExperiencia.getText();
        Experiencia e = new Experiencia(anios, cargo, cargo, anios, 0);

        experienciasLaboralesAgregadas.add(e);

        JOptionPane.showMessageDialog(null, "Experiencia agregada");
        txtCargoExperiencia.setText("Cargo?");
        txtLugarExperiencia.setText("Lugar?");
    }//GEN-LAST:event_btnAgregarExperienciaActionPerformed

    private void btnAgregarReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarReferenciaActionPerformed

        String nombre, apellido, cargo, telefono;
        nombre = txtNombreReferencia.getText();
        apellido = txtApellidoReferencia.getText();
        cargo = txtCargoReferencia.getText();
        telefono = txtTelefonoReferencia.getText();

        Referencia r = new Referencia(1, nombre, apellido, cargo, telefono, 0);

        referenciasAgregadas.add(r);
        txtNombreReferencia.setText("Nombre?");
        txtApellidoReferencia.setText("Apellido?");
        txtCargoReferencia.setText("Cargo?");
        txtTelefonoReferencia.setText("Telefono?");

        JOptionPane.showMessageDialog(null, "Referencia agregada");
    }//GEN-LAST:event_btnAgregarReferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void rellenarComboboxes() {
        cboDisponibilidad.removeAllItems();
        cboEstadoCivil.removeAllItems();
        cboNacionalidad.removeAllItems();
        cboNivelDeEstudio.removeAllItems();
        cboOcupacion.removeAllItems();
        cboIdiomas.removeAllItems();
        cboConInfo.removeAllItems();

        nacionalidades.add("Chilena");
        nacionalidades.add("Argentina");
        nacionalidades.add("Uruguaya");
        nacionalidades.add("Brasilera");
        nacionalidades.add("Estado unidense");
        nacionalidades.add("China");
        nacionalidades.add("Rusa");

        estadosCiviles.add("Soltero");
        estadosCiviles.add("Casado");
        estadosCiviles.add("Divorciado");

        nivelesDeEstudio.add("Básica en curso");
        nivelesDeEstudio.add("Básica completa");
        nivelesDeEstudio.add("Media en curso");
        nivelesDeEstudio.add("Básica completa");
        nivelesDeEstudio.add("Técnica en curso");
        nivelesDeEstudio.add("Técnica completa");
        nivelesDeEstudio.add("Profesional en curso");
        nivelesDeEstudio.add("Técnica completa");
        nivelesDeEstudio.add("Universitaria en curso");
        nivelesDeEstudio.add("Universitaria completa");
        nivelesDeEstudio.add("Magister");
        nivelesDeEstudio.add("Doctorado");

        ocupaciones.add("Desocupado");
        ocupaciones.add("Estudiante");
        ocupaciones.add("Estudiante con trabajo a tiempo parcial");
        ocupaciones.add("Estudiante con trabajo a tiempo completo");
        ocupaciones.add("Trabajador a tiempo parcial");
        ocupaciones.add("Trabajador a tiempo completo");

        disponibilidades.add("Vespertina");
        disponibilidades.add("Matutina");
        disponibilidades.add("Nocturna");
        disponibilidades.add("Todas las anteriores");

        for (String disponibilidad : disponibilidades) {
            cboDisponibilidad.addItem(disponibilidad);
        }

        for (String estadoCivil : estadosCiviles) {
            cboEstadoCivil.addItem(estadoCivil);
        }

        for (String nacionalidad : nacionalidades) {
            cboNacionalidad.addItem(nacionalidad);
        }

        for (String nivelDeEstudio : nivelesDeEstudio) {
            cboNivelDeEstudio.addItem(nivelDeEstudio);
        }

        for (String ocupacion : ocupaciones) {
            cboOcupacion.addItem(ocupacion);
        }

        for (Idioma idioma : idiomas) {
            cboIdiomas.addItem(idioma.getNombre());
        }

        for (ConocimientoDeInformatica conInfo : conocimientosDeInformatica) {
            cboConInfo.addItem(conInfo.getNombre());
        }

    }

    public class HiloParaRestaurar extends Thread {

        private Boolean detenido;
        private ManejoDeRespaldo mr = GUI.regulador;

        @Override
        public void run() {

            mr = new ManejoDeRespaldo();

            int i = 0;
            while (true) {

                try {
                    detenido = false;

                    mr.restaurarBD("respaldo.sql");

                    Thread.sleep(1000);
                    i++;

                    synchronized (cerrojo) {
                        if (detenido) {
                            try {
                                cerrojo.wait();
                            } catch (InterruptedException ex) {
                                Logger.getLogger(HiloParaRespaldar.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        }

                    }

                } catch (InterruptedException ex) {

                }
            }
        }

        public void detener() {
            detenido = true;
        }

        public void resumir() {

            synchronized (cerrojo) {
                detenido = false;
                cerrojo.notifyAll();
            }

        }

    }

    public class HiloParaRespaldar extends Thread {

        private Boolean detenido;
        private ManejoDeRespaldo mr = GUI.regulador;

        @Override
        public void run() {

            mr = new ManejoDeRespaldo();

            int i = 0;
            while (true) {

                try {
                    detenido = false;

                    mr.crearRespaldoBD();

                    Thread.sleep(10000);
                    i++;

                    synchronized (cerrojo) {
                        if (detenido) {
                            try {
                                cerrojo.wait();
                            } catch (InterruptedException ex) {
                                Logger.getLogger(HiloParaRespaldar.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        }

                    }

                } catch (InterruptedException ex) {

                }
            }
        }

        public void detener() {
            detenido = true;
        }

        public void resumir() {

            synchronized (cerrojo) {
                detenido = false;
                cerrojo.notifyAll();
            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarConocimientoInformatica;
    private javax.swing.JButton btnAgregarExperiencia;
    private javax.swing.JButton btnAgregarIdioma;
    private javax.swing.JButton btnAgregarReferencia;
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.JButton btn_crearPdf;
    private com.github.lgooddatepicker.components.CalendarPanel calendar;
    private javax.swing.JComboBox cboConInfo;
    private javax.swing.JComboBox cboDisponibilidad;
    private javax.swing.JComboBox cboEstadoCivil;
    private javax.swing.JComboBox cboIdiomas;
    private javax.swing.JComboBox cboNacionalidad;
    private javax.swing.JComboBox cboNivelDeEstudio;
    private javax.swing.JComboBox cboOcupacion;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblAñosExperiencia;
    private javax.swing.JLabel lblConocimientosDeInformatica;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDisponibilidad;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblExperiencia;
    private javax.swing.JLabel lblFechaDeNacimiento;
    private javax.swing.JLabel lblIdiomas;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JLabel lblNivelDeEstudio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOcupacion;
    private javax.swing.JLabel lblReferencias;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JRadioButton rbtFemenino;
    private javax.swing.JRadioButton rbtMasculino;
    private javax.swing.JSpinner spnAnios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoReferencia;
    private javax.swing.JTextField txtCargoExperiencia;
    private javax.swing.JTextField txtCargoReferencia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtLugarExperiencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreReferencia;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoReferencia;
    // End of variables declaration//GEN-END:variables
}
